In [3]:
from entsoe import EntsoePandasClient
import pandas as pd
API_KEY = '1134c6e2-51f3-419f-bd6d-189faec8df3f'

In [22]:
# Initialize the client with your API token
client = EntsoePandasClient(api_key=API_KEY)
# Specify the parameters for data retrieval
start_date = pd.Timestamp('2023-01-01',tz='Europe/Berlin')
end_date = pd.Timestamp('2023-01-05', tz='Europe/Berlin')
country_code = 'DE_LU'  # Germany - LU region

In [23]:
# Load Datasets
load_data = client.query_load(country_code, start=start_date,end=end_date)
load_forecast = client.query_load_forecast(country_code, start=start_date,end=end_date)
generation_data = client.query_generation(country_code, start=start_date,end=end_date)
generation_forecast = client.query_generation_forecast(country_code, start=start_date,end=end_date)
wind_and_solar_forecast = client.query_wind_and_solar_forecast(country_code, start=start_date,end=end_date)
day_ahead_prices = client.query_day_ahead_prices(country_code, start=start_date,end=end_date)

In [30]:
load_forecast

                           Forecasted Load
2023-01-01 00:00:00+01:00          43046.0
2023-01-01 00:15:00+01:00          42577.0
2023-01-01 00:30:00+01:00          41937.0
2023-01-01 00:45:00+01:00          41302.0
2023-01-01 01:00:00+01:00          40841.0
...                                    ...
2023-01-04 22:45:00+01:00          54961.0
2023-01-04 23:00:00+01:00          53925.0
2023-01-04 23:15:00+01:00          53106.0
2023-01-04 23:30:00+01:00          52115.0
2023-01-04 23:45:00+01:00          51439.0

[384 rows x 1 columns]

In [28]:
generation_data

                          Fossil Brown coal/Lignite        Fossil Gas  \
                                  Actual Aggregated Actual Aggregated
2023-01-01 00:00:00+01:00                    3851.0            2485.0
2023-01-01 00:15:00+01:00                    3853.0            2462.0
2023-01-01 00:30:00+01:00                    3866.0            2472.0
2023-01-01 00:45:00+01:00                    3867.0            2457.0
2023-01-01 01:00:00+01:00                    3876.0            2295.0
...                                             ...               ...
2023-01-04 22:45:00+01:00                    4775.0            2927.0
2023-01-04 23:00:00+01:00                    4814.0            2896.0
2023-01-04 23:15:00+01:00                    4825.0            2930.0
2023-01-04 23:30:00+01:00                    4796.0            2933.0
2023-01-04 23:45:00+01:00                    4794.0            2882.0

                           Fossil Hard coal        Fossil Oil  \
                          Actual Aggregated Actual Aggregated
2023-01-01 00:00:00+01:00            2068.0               8.0
2023-01-01 00:15:00+01:00            2072.0               8.0
2023-01-01 00:30:00+01:00            2068.0               8.0
2023-01-01 00:45:00+01:00            2062.0               8.0
2023-01-01 01:00:00+01:00            2053.0               8.0
...                                     ...               ...
2023-01-04 22:45:00+01:00            5754.0               8.0
2023-01-04 23:00:00+01:00            5661.0               8.0
2023-01-04 23:15:00+01:00            5564.0               8.0
2023-01-04 23:30:00+01:00            5512.0               8.0
2023-01-04 23:45:00+01:00            5521.0               8.0

                                 Geothermal Hydro Pumped Storage  \
                          Actual Aggregated    Actual Aggregated
2023-01-01 00:00:00+01:00              26.0                 54.0
2023-01-01 00:15:00+01:00              26.0                 39.0
2023-01-01 00:30:00+01:00              27.0                 39.0
2023-01-01 00:45:00+01:00              27.0                 39.0
2023-01-01 01:00:00+01:00              26.0                106.0
...                                     ...                  ...
2023-01-04 22:45:00+01:00              24.0                205.0
2023-01-04 23:00:00+01:00              24.0                208.0
2023-01-04 23:15:00+01:00              24.0                217.0
2023-01-04 23:30:00+01:00              24.0                220.0
2023-01-04 23:45:00+01:00              24.0                212.0

                                             Hydro Run-of-river and poundage  \
                          Actual Consumption               Actual Aggregated
2023-01-01 00:00:00+01:00             1699.0                          1217.0
2023-01-01 00:15:00+01:00             1774.0                          1215.0
2023-01-01 00:30:00+01:00             2185.0                          1215.0
2023-01-01 00:45:00+01:00             2076.0                          1213.0
2023-01-01 01:00:00+01:00              890.0                          1214.0
...                                      ...                             ...
2023-01-04 22:45:00+01:00             6658.0                          1208.0
2023-01-04 23:00:00+01:00             5600.0                          1204.0
2023-01-04 23:15:00+01:00             6347.0                          1204.0
2023-01-04 23:30:00+01:00             7074.0                          1207.0
2023-01-04 23:45:00+01:00             7395.0                          1210.0

                          Hydro Water Reservoir           Nuclear  \
                              Actual Aggregated Actual Aggregated
2023-01-01 00:00:00+01:00                  83.0            2461.0
2023-01-01 00:15:00+01:00                  76.0            2459.0
2023-01-01 00:30:00+01:00                  75.0            2460.0
2023-01-01 00:45:00+01:00                  94.0            2458.0
2023-01-01 01:00:00+01:00                  68.0            2458.0
...                                         ...               ...
2023-01-04 22:45:00+01:00                  62.0            2417.0
2023-01-04 23:00:00+01:00                  64.0            2417.0
2023-01-04 23:15:00+01:00                  73.0            2419.0
2023-01-04 23:30:00+01:00                  76.0            2416.0
2023-01-04 23:45:00+01:00                  70.0            2412.0

                                      Other   Other renewable  \
                          Actual Aggregated Actual Aggregated
2023-01-01 00:00:00+01:00             187.0             103.0
2023-01-01 00:15:00+01:00             187.0             103.0
2023-01-01 00:30:00+01:00             187.0             103.0
2023-01-01 00:45:00+01:00             187.0             103.0
2023-01-01 01:00:00+01:00             187.0             103.0
...                                     ...               ...
2023-01-04 22:45:00+01:00             193.0             102.0
2023-01-04 23:00:00+01:00             193.0             103.0
2023-01-04 23:15:00+01:00             194.0             103.0
2023-01-04 23:30:00+01:00             194.0             103.0
2023-01-04 23:45:00+01:00             194.0             103.0

                                      Solar                     \
                          Actual Aggregated Actual Consumption
2023-01-01 00:00:00+01:00               0.0                0.0
2023-01-01 00:15:00+01:00               0.0                0.0
2023-01-01 00:30:00+01:00               0.0                0.0
2023-01-01 00:45:00+01:00               0.0                0.0
2023-01-01 01:00:00+01:00               0.0                0.0
...                                     ...                ...
2023-01-04 22:45:00+01:00               0.0                0.0
2023-01-04 23:00:00+01:00               0.0                0.0
2023-01-04 23:15:00+01:00               0.0                0.0
2023-01-04 23:30:00+01:00               0.0                0.0
2023-01-04 23:45:00+01:00               0.0                0.0

                                      Waste     Wind Offshore  \
                          Actual Aggregated Actual Aggregated
2023-01-01 00:00:00+01:00             748.0            2737.0
2023-01-01 00:15:00+01:00             747.0            2974.0
2023-01-01 00:30:00+01:00             752.0            3268.0
2023-01-01 00:45:00+01:00             744.0            3258.0
2023-01-01 01:00:00+01:00             746.0            3142.0
...                                     ...               ...
2023-01-04 22:45:00+01:00             551.0            5069.0
2023-01-04 23:00:00+01:00             554.0            4931.0
2023-01-04 23:15:00+01:00             554.0            4992.0
2023-01-04 23:30:00+01:00             554.0            5004.0
2023-01-04 23:45:00+01:00             556.0            4697.0

                               Wind Onshore
                          Actual Aggregated Actual Consumption
2023-01-01 00:00:00+01:00           28627.0                0.0
2023-01-01 00:15:00+01:00           28676.0                0.0
2023-01-01 00:30:00+01:00           29249.0                0.0
2023-01-01 00:45:00+01:00           28457.0                0.0
2023-01-01 01:00:00+01:00           29329.0                0.0
...                                     ...                ...
2023-01-04 22:45:00+01:00           43065.0                0.0
2023-01-04 23:00:00+01:00           42805.0                0.0
2023-01-04 23:15:00+01:00           42291.0                0.0
2023-01-04 23:30:00+01:00           41807.0                0.0
2023-01-04 23:45:00+01:00           41763.0                0.0

[384 rows x 18 columns]

In [29]:
generation_forecast

2023-01-01 00:00:00+01:00    56100.0
2023-01-01 01:00:00+01:00    56301.0
2023-01-01 02:00:00+01:00    53753.0
2023-01-01 03:00:00+01:00    52794.0
2023-01-01 04:00:00+01:00    52020.0
                              ...
2023-01-04 19:00:00+01:00    78449.0
2023-01-04 20:00:00+01:00    75516.0
2023-01-04 21:00:00+01:00    73283.0
2023-01-04 22:00:00+01:00    70713.0
2023-01-04 23:00:00+01:00    68643.0
Freq: 60T, Name: Actual Aggregated, Length: 96, dtype: float64

In [34]:
from datetime import datetime
start_time = pd.Timestamp('2023-01-01', tz='Europe/Berlin')
end_time = pd.Timestamp('2023-06-01', tz='Europe/Berlin')

In [17]:
from dwdweather import DwdWeather
import datetime
import pandas as pd

# Define station_id for each city (these are examples and need to be replaced)
station_ids = {
    "Munich": 2667,
    "Berlin": 1048,
    "Frankfurt": 2483
}

# Define timestamps
start_time = datetime.datetime(2023, 1, 1)
end_time = datetime.datetime(2023, 6, 1)

# Create a DwdWeather object
dw = DwdWeather()

# Empty list to store the data
data = []

# Get data for each city
for city, station_id in station_ids.items():
    timestamp = start_time
    while timestamp <= end_time:
        # Query data for specific station and timestamp
        res = dw.query(station_id, timestamp)
        
        # Check if data is not None
        if res is not None:
            # Add city name, timestamp and weather data to the list
            row = [city, timestamp] + list(res.values())
            data.append(row)
        
        # Increment timestamp by one hour
        timestamp += datetime.timedelta(hours=1)

# Column names: city, timestamp, and weather data keys
columns = ["City", "Timestamp"] + list(res.keys())

# Convert the list to a DataFrame
df = pd.DataFrame(data, columns=columns)

# Pivot the DataFrame
pivot_df = df.pivot(index='Timestamp', columns='City')

# Save the DataFrame to a CSV file
pivot_df.to_csv("weather_data.csv")

KeyboardInterrupt:

In [ ]:
df

                    station_id                     datetime              \
City                    Berlin Frankfurt Munich      Berlin   Frankfurt
Timestamp
2023-01-01 00:00:00       1048      2483   2667  2023010100  2023010100
2023-01-01 01:00:00       1048      2483   2667  2023010101  2023010101
2023-01-01 02:00:00       1048      2483   2667  2023010102  2023010102
2023-01-01 03:00:00       1048      2483   2667  2023010103  2023010103
2023-01-01 04:00:00       1048      2483   2667  2023010104  2023010104
...                        ...       ...    ...         ...         ...
2023-05-31 20:00:00       1048      2483   2667  2023053120  2023053120
2023-05-31 21:00:00       1048      2483   2667  2023053121  2023053121
2023-05-31 22:00:00       1048      2483   2667  2023053122  2023053122
2023-05-31 23:00:00       1048      2483   2667  2023053123  2023053123
2023-06-01 00:00:00       1048      2483   2667  2023060100  2023060100

                                air_temperature_quality_level            \
City                     Munich                        Berlin Frankfurt
Timestamp
2023-01-01 00:00:00  2023010100                             3         3
2023-01-01 01:00:00  2023010101                             3         3
2023-01-01 02:00:00  2023010102                             3         3
2023-01-01 03:00:00  2023010103                             3         3
2023-01-01 04:00:00  2023010104                             3         3
...                         ...                           ...       ...
2023-05-31 20:00:00  2023053120                             1         1
2023-05-31 21:00:00  2023053121                             1         1
2023-05-31 22:00:00  2023053122                             1         1
2023-05-31 23:00:00  2023053123                             1         1
2023-06-01 00:00:00  2023060100                             1         1

                           air_temperature_200  ... visibility_value  \
City                Munich              Berlin  ...           Munich
Timestamp                                       ...
2023-01-01 00:00:00      3                16.1  ...          27050.0
2023-01-01 01:00:00      3                16.1  ...          53520.0
2023-01-01 02:00:00      3                15.4  ...          60300.0
2023-01-01 03:00:00      3                15.1  ...          63790.0
2023-01-01 04:00:00      3                15.4  ...          64450.0
...                    ...                 ...  ...              ...
2023-05-31 20:00:00      1                19.6  ...          57790.0
2023-05-31 21:00:00      1                18.7  ...          58330.0
2023-05-31 22:00:00      1                16.3  ...          61380.0
2023-05-31 23:00:00      1                16.4  ...          64120.0
2023-06-01 00:00:00      1                13.1  ...          54010.0

                    wind_quality_level                  wind_speed            \
City                            Berlin Frankfurt Munich     Berlin Frankfurt
Timestamp
2023-01-01 00:00:00                  3         3      3        6.0      12.3
2023-01-01 01:00:00                  3         3      3        6.5      11.6
2023-01-01 02:00:00                  3         3      3        6.2      10.7
2023-01-01 03:00:00                  3         3      3        6.1      11.8
2023-01-01 04:00:00                  3         3      3        6.4      11.4
...                                ...       ...    ...        ...       ...
2023-05-31 20:00:00                  1         1      1        0.9       5.1
2023-05-31 21:00:00                  1         1      1        1.5       5.8
2023-05-31 22:00:00                  1         1      1        1.1       5.5
2023-05-31 23:00:00                  1         1      1        0.8       4.6
2023-06-01 00:00:00                  1         1      1        2.0       3.8

                           wind_direction
City                Munich         Berlin Frankfurt Munich
Timestamp
2023-01-01 00:00:00    5.8          200.0     220.0  190.0
2023-01-01 01:00:00    5.3          210.0     230.0  190.0
2023-01-01 02:00:00    5.5          210.0     220.0  200.0
2023-01-01 03:00:00    5.4          190.0     220.0  200.0
2023-01-01 04:00:00    6.4          190.0     220.0  200.0
...                    ...            ...       ...    ...
2023-05-31 20:00:00    4.4          350.0      40.0   30.0
2023-05-31 21:00:00    3.9          360.0      30.0   30.0
2023-05-31 22:00:00    4.6          340.0      30.0   50.0
2023-05-31 23:00:00    3.8          330.0      20.0   70.0
2023-06-01 00:00:00    2.3          170.0      10.0  100.0

[3625 rows x 111 columns]

In [38]:
df

,City,Timestamp,station_id,datetime,air_temperature_quality_level,air_temperature_200,relative_humidity_200,cloudiness_quality_level,cloudiness_source,cloudiness_total_cover,...,solar_zenith,solar_end_of_interval,sun_quality_level,sun_duration,visibility_quality_level,visibility_source,visibility_value,wind_quality_level,wind_speed,wind_direction
0,Munich,2023-01-01 00:00:00,2667,2023010100,3,15.3,53.0,3,I,8,...,NaN,NaN,NaN,NaN,3.0,I,27050.0,3,5.8,190.0
1,Munich,2023-01-01 01:00:00,2667,2023010101,3,15.0,52.0,3,I,7,...,NaN,NaN,NaN,NaN,3.0,I,53520.0,3,5.3,190.0
2,Munich,2023-01-01 02:00:00,2667,2023010102,3,14.5,52.0,3,I,8,...,NaN,NaN,NaN,NaN,3.0,I,60300.0,3,5.5,200.0
3,Munich,2023-01-01 03:00:00,2667,2023010103,3,14.9,49.0,3,I,8,...,NaN,NaN,3.0,0.0,3.0,I,63790.0,3,5.4,200.0
4,Munich,2023-01-01 04:00:00,2667,2023010104,3,14.9,51.0,3,I,8,...,NaN,NaN,3.0,0.0,3.0,I,64450.0,3,6.4,200.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10870,Frankfurt,2023-05-31 20:00:00,2483,2023053120,1,13.4,68.0,1,I,8,...,NaN,NaN,1.0,19.0,1.0,I,52800.0,1,5.1,40.0
10871,Frankfurt,2023-05-31 21:00:00,2483,2023053121,1,13.0,69.0,1,I,1,...,NaN,NaN,1.0,0.0,1.0,I,69050.0,1,5.8,30.0
10872,Frankfurt,2023-05-31 22:00:00,2483,2023053122,1,12.7,69.0,1,I,0,...,NaN,NaN,1.0,0.0,1.0,I,59930.0,1,5.5,30.0
10873,Frankfurt,2023-05-31 23:00:00,2483,2023053123,1,12.1,72.0,1,I,2,...,NaN,NaN,1.0,0.0,1.0,I,69870.0,1,4.6,20.0
10874,Frankfurt,2023-06-01 00:00:00,2483,2023060100,1,11.3,76.0,1,I,1,...,NaN,NaN,1.0,0.0,1.0,I,64510.0,1,3.8,10.0

In [11]:
import pandas as pd
import numpy as np
df = pd.read_csv('/home/mamur/EON/forecast-electricity-prices/src/data/weather_data.csv', index_col=0, parse_dates=True)

/tmp/ipykernel_177632/3476391921.py:3: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df = pd.read_csv('/home/mamur/EON/forecast-electricity-prices/src/data/weather_data.csv', index_col=0, parse_dates=True)

In [12]:
relevant_columns = [
    'air_temperature_200', 'visibility_value', 'wind_speed', 'wind_direction',
    'air_temperature_200.1', 'visibility_value.1', 'wind_speed.1', 'wind_direction.1',
    'air_temperature_200.2', 'visibility_value.2', 'wind_speed.2', 'wind_direction.2'
]
df = df[relevant_columns]
df = df.iloc[2:]

In [13]:
import pandas as pd

df2 = df.iloc[2:]
# Rename columns for clarity
df2.columns = ['air_temperature_berlin', 'visibility_berlin', 'wind_speed_berlin', 'wind_direction_berlin',
              'air_temperature_frankfurt', 'visibility_frankfurt', 'wind_speed_frankfurt', 'wind_direction_frankfurt',
              'air_temperature_munich', 'visibility_munich', 'wind_speed_munich', 'wind_direction_munich']

# Check the result
print(df2.head())

                    air_temperature_berlin visibility_berlin  \
2023-01-01 02:00:00                   15.4           53430.0
2023-01-01 03:00:00                   15.1           61190.0
2023-01-01 04:00:00                   15.4           72030.0
2023-01-01 05:00:00                   14.6           58350.0
2023-01-01 06:00:00                   15.1           65240.0

                    wind_speed_berlin wind_direction_berlin  \
2023-01-01 02:00:00               6.2                 210.0
2023-01-01 03:00:00               6.1                 190.0
2023-01-01 04:00:00               6.4                 190.0
2023-01-01 05:00:00               6.1                 190.0
2023-01-01 06:00:00               6.2                 210.0

                    air_temperature_frankfurt visibility_frankfurt  \
2023-01-01 02:00:00                       8.5              62460.0
2023-01-01 03:00:00                       8.6              75000.0
2023-01-01 04:00:00                       8.3              73380.0
2023-01-01 05:00:00                       8.0              70050.0
2023-01-01 06:00:00                       7.9              59200.0

                    wind_speed_frankfurt wind_direction_frankfurt  \
2023-01-01 02:00:00                 10.7                    220.0
2023-01-01 03:00:00                 11.8                    220.0
2023-01-01 04:00:00                 11.4                    220.0
2023-01-01 05:00:00                 10.4                    220.0
2023-01-01 06:00:00                 10.3                    220.0

                    air_temperature_munich visibility_munich  \
2023-01-01 02:00:00                   14.5           60300.0
2023-01-01 03:00:00                   14.9           63790.0
2023-01-01 04:00:00                   14.9           64450.0
2023-01-01 05:00:00                   14.5           63340.0
2023-01-01 06:00:00                   14.2           67640.0

                    wind_speed_munich wind_direction_munich
2023-01-01 02:00:00               5.5                 200.0
2023-01-01 03:00:00               5.4                 200.0
2023-01-01 04:00:00               6.4                 200.0
2023-01-01 05:00:00               5.9                 200.0
2023-01-01 06:00:00               5.9                 190.0

In [14]:
df2

,air_temperature_berlin,visibility_berlin,wind_speed_berlin,wind_direction_berlin,air_temperature_frankfurt,visibility_frankfurt,wind_speed_frankfurt,wind_direction_frankfurt,air_temperature_munich,visibility_munich,wind_speed_munich,wind_direction_munich
2023-01-01 02:00:00,15.4,53430.0,6.2,210.0,8.5,62460.0,10.7,220.0,14.5,60300.0,5.5,200.0
2023-01-01 03:00:00,15.1,61190.0,6.1,190.0,8.6,75000.0,11.8,220.0,14.9,63790.0,5.4,200.0
2023-01-01 04:00:00,15.4,72030.0,6.4,190.0,8.3,73380.0,11.4,220.0,14.9,64450.0,6.4,200.0
2023-01-01 05:00:00,14.6,58350.0,6.1,190.0,8.0,70050.0,10.4,220.0,14.5,63340.0,5.9,200.0
2023-01-01 06:00:00,15.1,65240.0,6.2,210.0,7.9,59200.0,10.3,220.0,14.2,67640.0,5.9,190.0
...,...,...,...,...,...,...,...,...,...,...,...,...
2023-05-31 20:00:00,19.6,60010.0,0.9,350.0,13.4,52800.0,5.1,40.0,20.0,57790.0,4.4,30.0
2023-05-31 21:00:00,18.7,60680.0,1.5,360.0,13.0,69050.0,5.8,30.0,18.2,58330.0,3.9,30.0
2023-05-31 22:00:00,16.3,61050.0,1.1,340.0,12.7,59930.0,5.5,30.0,18.4,61380.0,4.6,50.0
2023-05-31 23:00:00,16.4,71770.0,0.8,330.0,12.1,69870.0,4.6,20.0,17.4,64120.0,3.8,70.0
2023-06-01 00:00:00,13.1,52340.0,2.0,170.0,11.3,64510.0,3.8,10.0,15.9,54010.0,2.3,100.0